### ISSUE TITLE
centos

### ISSUE THREAD

**Issue by richhl** [geerlingguy/ansible-role-drupal#11]
hi jeff proud reader of your book :+1: 

you have said:

"Currently the role is only guaranteed to work on a LAMP stack on Debian/Ubuntu, though only minimal changes will need to be made to make the role with other platforms (notably RedHat/CentOS), and with other webservers besides Apache (thus enabling Drupal on a LEMP stack fairly easily)."

would you please guide me about implementing that changes...i need this working for a centos 6.4

thx in advance.

**Comment by frob** [comment]
This would be great. I am guessing (not looked at code yet) that it is as simple as changing apache to httpd somewhere.

**Comment by geerlingguy** [comment]
Yeah, a lot of this is simple enough... I just haven't had the time to refactor this role yet—there are some other things I want to change at a more basic level to do things like make updates easier, make it work with composer/drush/etc. workflows, etc.

**Comment by geerlingguy** [comment]
Closing this out, as I'm working on completely rewriting the role for the next release, so it will work a lot more smoothly with multiple Drupal workflows (especially focused on Drupal 8, but also for D7 and somewhat D6). See: https://github.com/geerlingguy/ansible-role-drupal/issues/23
