### ISSUE TITLE
mysql restart not working and drupal not finding mysql.sock

### ISSUE THREAD

**Issue by richhl** [geerlingguy/ansible-role-drupal#12]
To reproduce:

-Execute README.md playbook example against https://vagrantcloud.com/xezpeleta/boxes/wheezy64
-got 

NOTIFIED: [geerlingguy.mysql | restart mysql] ********************************\* 
failed: [192.168.33.11] => {"failed": true}
msg: Stopping MySQL database server: mysqld.
Starting MySQL database server: mysqld . . . . . . . . . . . . . . failed!

-I have opened an ssh session against th VM and restarted mysql from command line. It works....
-but http://drupaltest.dev throws error in attached image.
![drupal_cannot_connect_mysql](https://cloud.githubusercontent.com/assets/1074446/5314695/3f4ffe40-7c75-11e4-92b2-8ebe84d8299c.png)

**Comment by geerlingguy** [comment]
Closing this out, as I'm working on completely rewriting the role for the next release, so it will work a lot more smoothly with multiple Drupal workflows (especially focused on Drupal 8, but also for D7 and somewhat D6). See: https://github.com/geerlingguy/ansible-role-drupal/issues/23
