### ISSUE TITLE
Deploying updates?

### ISSUE THREAD

**Issue by pmackay** [geerlingguy/ansible-role-drupal#13]
Hi Jeff, I'm just wondering if you've done any work on Drupal deployment updates? This role is great for deploying a new site, but different processes would be needed to:
- install an existing site onto a new server
- run updates on that site

Any feedback much appreciated :)

**Comment by geerlingguy** [comment]
Just FYI, I'm planning on refactoring this role a bit sometime soon... Not exactly sure when, but it will be a lot more robust, support updates, drush, etc. a lot nicer.

**Comment by geerlingguy** [comment]
Closing this out, as I'm working on completely rewriting the role for the next release, so it will work a lot more smoothly with multiple Drupal workflows (especially focused on Drupal 8, but also for D7 and somewhat D6). See: https://github.com/geerlingguy/ansible-role-drupal/issues/23
