### ISSUE TITLE
000-default.conf not removed

### ISSUE THREAD

**Issue by ford-thomas-w** [geerlingguy/ansible-role-drupal#14]
Looks like it is just missing the ".conf" portion:

```yaml
    - name: Remove default virtualhost file.
      file: >
        path=/etc/apache2/sites-enabled/000-default
        state=absent
      notify: restart webserver

**Comment by geerlingguy** [comment]
The [Apache](https://github.com/geerlingguy/ansible-role-apache) role includes this functionality out of the box, just set `apache_remove_default_vhost: true` in your playbook config, and it should work.
