### ISSUE TITLE
Failed opening autoload.php

### ISSUE THREAD

**Issue by hajaalin** [geerlingguy/ansible-role-drupal#22]
The `Install Drupal` task fails like this:

```
root@drupal:/var/www/drupal-7.x-dev# drush si standard -y --site-name="Drupal Example" --account-name=admin --account-pass=admin --db-url=mysql://drupal:password@localhost/drupal 
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
 [warning] require(/var/www/drupal-7.x-dev/autoload.php): failed to open stream: No such file or directory drupal.inc:17
PHP Fatal error:  require(): Failed opening required '/var/www/drupal-7.x-dev/autoload.php' (include_path='.:/usr/share/php') in /usr/local/share/drush/includes/drupal.inc on line 17
 [error]  Drush command terminated abnormally due to an unrecoverable error.
Error: require(): Failed opening required '/var/www/drupal-7.x-dev/autoload.php' (include_path='.:/usr/share/php') in /usr/local/share/drush/includes/drupal.inc, line 17 
```

This is on VirtualBox, Vagrant box 'bento/ubuntu-16.04'.

**Comment by geerlingguy** [comment]
@hajaalin - It looks like it's trying to install Drupal 7.x (and not 8.x). I'm assuming you changed `drupal_core_version` to `7.x`, is that correct?

I haven't tested Drupal 7 with this role in some time, so I'm not 100% it's working correctly.

**Comment by hajaalin** [comment]
Hi Jeff, yes, that's correct, I need to use 7.x. I'm trying to build a test site, and that's the version the real server is using.

I also found your drupal-vm project, I'll try it as well. We could probably use my computer as the test server. This is just for a very small team, to sketch our new pages.

________________________________________

**Comment by geerlingguy** [comment]
Closing this out, as I'm working on completely rewriting the role for the next release, so it will work a lot more smoothly with multiple Drupal workflows (especially focused on Drupal 8, but also for D7 and somewhat D6). See: https://github.com/geerlingguy/ansible-role-drupal/issues/23
