### ISSUE TITLE
Add automated test for deployment with updates to Drupal codebase

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-drupal#33]
This one may be slightly tricky, unless we add in some extra jiggery-pokery to the `test-deploy.yml` playbook that was added in #24.

Basically, we need the deployment test to do the following:

  1. Deploy Drupal using a Git-based codebase.
  2. Install Drupal using that same codebase.
  3. Update Drupal using that same codebase (based on a later commit in the Git repo).

Maybe we could do this by telling the `test-deploy.yml` test to deploy one hash or tag, then have it deploy the next hash or tag. It doesn't even need to have a substantial change to test things are working correctly...

**Comment by kentr** [comment]
I've got something near this going [here](https://github.com/kentr/drupal-vm/blob/run-updates/provisioning/run-updates.yml) for security updates and my personal post-update testing setup.

It assumes that the DB has already been installed and the site is fully-functional before running the update playbook, but I'd like to automate the whole process starting from scratch.

I didn't see this in the docs: Is there a feature in DrupalVM for automatically importing a DB?

**Comment by geerlingguy** [comment]
@kentr - At this time, there isn't any db loading mechanism built into Drupal VM. The best suggestions are to either

  - Install fresh every time you bring up an instance (if your project works like that, and you don't have dependencies on content in the database).
  - Use a tool like Acquia's BLT to do this (e.g. `blt local:refresh` will pull down a prod db, or `blt local:setup` will install a fresh instance).
  - Use `drush sql-sync` or some other tool to do the local import from somewhere else.

**Comment by kentr** [comment]
Yeah, thx.  I use `sql-sync` manually, but was hoping there was some automation already built-in that I had missed.

**Comment by kentr** [comment]
I think I misunderstood the goal of this issue...  

Is the goal to have a test for the role itself (and not to add automated testing as a step that the role executes after it does codebase updates)?

**Comment by geerlingguy** [comment]
@kentr - Yes, the goal here is to make sure this role has a test for itself that runs in Travis CI.
