### ISSUE TITLE
Allow playbook to specify extra tasks to run post-deploy-code-update

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-drupal#34]
It might just be a variable like:

```yaml
drupal_deploy_update_tasks:
  - drush cim -y
  - drush [etc]
```

But basically, see: https://github.com/geerlingguy/ansible-role-drupal/blob/master/tasks/update.yml#L7-L8

**Comment by bryanbraun** [comment]
I like this!

What do you think about having `updatedb` and `cache-rebuild` in this list as well (perhaps as the default tasks). That way downstream users can reorganize those if needed.

**Comment by geerlingguy** [comment]
@bryanbraun - Definitely yes to `updb`... for `cache-rebuild`, I don't know if I want to default to `cr` which only works on D8, figure out some way to support `cc all` on D < 8 and `cr` on D == 8, or just leave out the cache rebuild.

There are still a lot of people using D7 :(
