### ISSUE TITLE
Locally reference patches in Makefile aren't applied

### ISSUE THREAD

**Issue by Chapabu** [geerlingguy/ansible-role-drupal#52]
The first step under `tasks/build-makefile.yml` copies a specified makefile into `/tmp`. If the specified makefile contains relative paths to patches, they then do not resolve.

E.g. Given the following pseudo makefile:

```yml
oa_files:
  subdir: 'oa-patched'
  version: 3.16
  patch:
    - 'some/patch/that/has/to/be/local.patch'
```

This works:

```bash
drush make my-makefile.make.yml docroot
```

But when provisioned via DrupalVM (which is how I noticed this error):

```bash
failed to open stream: No such file or directory drush.inc:766
Unable to download /tmp/some/patch/that/has/to/be/local.patch
```

I managed to get around it in my use case by setting `drupal_build_makefile` to `false` and just installing in a post-provision script.

To be honest, I think the actual solution is to update the docs for DrupalVM (and/or this role) to say something along the lines of "If you have local patches and you're building with a makefile, please build via a post-provision script) - as it's a lot of effort to fix, and Composer has superceded makefiles moving forward. Other alternatives would be adding reading makefiles (but then you have to cater for `ini` and `yml` format) or building in place (means a big change in behaviour).

Either way, if you let me know your preference and I'll help where I can :)

**Comment by geerlingguy** [comment]
@Chapabu - Definitely! And yes, probably the easiest solution (in terms of maintaining this going forward) would be to recommend handling it custom in a post-provision task or shell script. If you want to add the verbiage in the docs, I'll merge it!
