### ISSUE TITLE
Add the ability to disable composer install during deployment.

### ISSUE THREAD

**Issue by Graloth** [geerlingguy/ansible-role-drupal#53]
> Currently with the drupal role, it's assumed that if there is a composer.json, and the codebase is being deployed via Git(`drupal_deploy: true`), then `composer install` should be run
> - *Reference: https://github.com/geerlingguy/drupal-vm/issues/1500#issuecomment-319972627*  

My current need is to be able to disable the use of `composer install` when deploying from git, as I need to make some edits to my current composer.json file before manually running it (I am working on getting the composer.json working, but it's a complex project with a lot of custom code).

A config option, such as `drupal_composer_install_after_deploy` that could be set to `true`/`false` or `yes`/`no` would be great.

**Comment by geerlingguy** [comment]
I, uh, need this now. So I'll do it now :D
