### ISSUE TITLE
Role breaks when executed with include_role

### ISSUE THREAD

**Issue by popstas** [geerlingguy/ansible-role-drupal#57]
Hello, I have role `site`, it executes other roles with `include_role`.
When I added `tasks/drupal.yml`:
``` yaml
- name: Setup drupal
  include_role:
    name: drupal
  vars:
    ...
```

It fails at task files include:

```
TASK [drupal : include] **************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "reason": "the file_name '/home/popstas/projects/ansible/viasite-ansible/ansible-server/playbooks/roles/tasks/build-makefile.yml' does not exist, or is not readable"}
```

When I replaced:
``` yaml
- include: tasks/build-makefile.yml
```

to:
``` yaml
- include: build-makefile.yml
```

Do you want to merge PR with fix?

**Comment by geerlingguy** [comment]
@popstas - That seems like it would be a bug upstream in Ansible. Also, are you saying that `- include: tasks/build-makefile.yml` worked, and `- include: build-makefile.yml` didn't? Or vice-versa?

See: https://github.com/ansible/ansible/issues/21328 — I'm inclined to close this since I don't want to change (and potentially break) how this role works on a modular level. Instead, I'd recommend posting in that upstream Ansible issue and testing any potential fixes that result from that thread.

**Comment by popstas** [comment]
`- include: tasks/build-makefile.yml` - not worked

`- include: build-makefile.yml` - worked

Thank you, agreed, ansible/ansible#21328 seems same bug.

Anyway, I'm using about 10 your roles and don't seen `- include: tasks/...` in other your `main.yml`.

**Comment by korzh-nick** [comment]
I confirm

> - include: tasks/build-makefile.yml - not worked
> - include: build-makefile.yml - worked

ansible 2.4.1
ansible-lint 3.4.15

```
[kalebas@mate drupal-vm]$ ansible-lint provisioning/playbook.yml
WARNING: Couldn't open /home/kalebas/Desktop/staff/ansible/drupal-vm/provisioning/roles/geerlingguy.drupal/tasks/tasks/deploy.yml - No such file or directory
WARNING: Couldn't open /home/kalebas/Desktop/staff/ansible/drupal-vm/provisioning/roles/geerlingguy.drupal/tasks/tasks/update.yml - No such file or directory
WARNING: Couldn't open /home/kalebas/Desktop/staff/ansible/drupal-vm/provisioning/roles/geerlingguy.drupal/tasks/tasks/build-makefile.yml - No such file or directory
WARNING: Couldn't open /home/kalebas/Desktop/staff/ansible/drupal-vm/provisioning/roles/geerlingguy.drupal/tasks/tasks/build-composer.yml - No such file or directory
WARNING: Couldn't open /home/kalebas/Desktop/staff/ansible/drupal-vm/provisioning/roles/geerlingguy.drupal/tasks/tasks/build-composer-project.yml - No such file or directory
WARNING: Couldn't open /home/kalebas/Desktop/staff/ansible/drupal-vm/provisioning/roles/geerlingguy.drupal/tasks/tasks/install-site.yml - No such file or directory
```
