### ISSUE TITLE
Sendmail config?

### ISSUE THREAD

**Issue by ElijahLynn** [geerlingguy/ansible-role-drupal#74]
I saw this commit that is installing `sendmail`. I need to configure `sendmail` to use a custom SMTP server and wonder if we should put an option in this module to configure it here too, since we are installing it here?

Thoughts?

**Comment by geerlingguy** [comment]
Note that the sendmail install is only in the test setup for molecule testing (https://github.com/geerlingguy/ansible-role-drupal/blob/b21f2373a76b523bc6c7868f15eba099d095d5ed/molecule/default/test-setup.yml); it's not part of the role proper, as the role assumes you have a mail setup that's adequate for Drupal already.

**Comment by ElijahLynn** [comment]
Thanks, I'll have to do some more sleuthing on what role is installing sendmail in our setup. Sorry for the noise.

**Comment by geerlingguy** [comment]
No problem!
