### ISSUE TITLE
The zip extension and unzip command are both missing

### ISSUE THREAD

**Issue by pjoulot** [geerlingguy/ansible-role-drupal#75]
I used that profile without any customization and the install fail when the task "Generate Drupal project with composer package in /tmp/composer-project" is running.

I got that error:
`FAILED! => {"changed": true, "cmd": ["/usr/local/bin/composer", "create-project", "drupal/recommended-project:^8@dev", "/tmp/composer-project", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:08.542105", "end": "2020-01-31 18:51:34.881682", "msg": "non-zero return code", "rc": 1, "start": "2020-01-31 18:51:26.339577", "stderr": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nInstalling drupal/recommended-project (8.9.x-dev cfb53224fe4a3cbfc925404f20376045387d17a7)\n    Failed to download drupal/recommended-project from dist: The zip extension and unzip command are both missing, skipping.\nYour command-line PHP is using multiple ini files. Run `php --ini` to show them.\n    Now trying to download from source\n  - Installing drupal/recommended-project (8.9.x-dev cfb5322): Cloning cfb53224fe\n\n                                                                                                                                          \n  [RuntimeException]                                                                                                                      \n  Failed to clone https://github.com/drupal/recommended-project.git, git was not found, check that it is installed and in your PATH env.  \n                                                                                                                                          \n  sh: 1: git: not found                                                                                                                   \n                                                                                                                                          \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stderr_lines": ["Do not run Composer as root/super user! See https://getcomposer.org/root for details", "Installing drupal/recommended-project (8.9.x-dev cfb53224fe4a3cbfc925404f20376045387d17a7)", "    Failed to download drupal/recommended-project from dist: The zip extension and unzip command are both missing, skipping.", "Your command-line PHP is using multiple ini files. Run `php --ini` to show them.", "    Now trying to download from source", "  - Installing drupal/recommended-project (8.9.x-dev cfb5322): Cloning cfb53224fe", "", "                                                                                                                                          ", "  [RuntimeException]                                                                                                                      ", "  Failed to clone https://github.com/drupal/recommended-project.git, git was not found, check that it is installed and in your PATH env.  ", "                                                                                                                                          ", "  sh: 1: git: not found                                                                                                                   ", "                                                                                                                                          ", "", "create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]"], "stdout": "", "stdout_lines": []}`

I guess we just need to add a command to install the package or we can use the role 
[ansible-role-zip](https://github.com/nephelaiio/ansible-role-zip) 

But I think that the dependency N/A on the page of the project is not true.

**Comment by pjoulot** [comment]
Maybe I did something wrong or missing something. I had the same problem with git, I had to add 
https://galaxy.ansible.com/geerlingguy/git

**Comment by geerlingguy** [comment]
For any environment which doesn't have unzip or anything similar installed, you'll end up with this error. It's a more basic requirement of the server environment where Drupal is running, and depending on how you use the role, you may or may not even run into that dependency, therefore this role is not technically dependent on another.

If the OS or hosting environment I'm using is missing these basic utilities, I generally add a task in my playbook to install them, like:

```yaml
- name: Install basic utilities
  package:
    name: unzip
    state: present
```
